# Generated by Django 5.0 on 2023-12-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elasticsearchApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdminFname', models.CharField(max_length=100)),
                ('AdminLname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderatorFname', models.CharField(max_length=100)),
                ('moderatorLname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('gmail', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(default='user', max_length=50)),
                ('favorite_articles', models.ManyToManyField(blank=True, related_name='favorited_by', to='elasticsearchApp.article')),
                ('saved_articles', models.ManyToManyField(blank=True, related_name='saved_by', to='elasticsearchApp.article')),
            ],
        ),
    ]
