# Generated by Django 5.0 on 2023-12-26 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaperHub', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Moderator',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
