# Generated by Django 5.0 on 2024-01-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaperHub', '0011_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderator',
            name='moderatorFname',
        ),
        migrations.RemoveField(
            model_name='moderator',
            name='moderatorLname',
        ),
    ]
