# Generated by Django 5.0 on 2023-12-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperHub', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperhubuser',
            name='gmail',
        ),
        migrations.AlterField(
            model_name='paperhubuser',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
