# Generated by Django 5.0 on 2023-12-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperHub', '0008_remove_paperhubuser_gmail_alter_paperhubuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperhubuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
