# Generated by Django 5.0 on 2023-12-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('auteurs', models.CharField(max_length=255)),
                ('institutions', models.CharField(max_length=255)),
                ('resume', models.TextField()),
                ('contenu', models.TextField()),
                ('references', models.CharField(max_length=255)),
                ('motsCles', models.CharField(max_length=255)),
                ('urlPDF', models.CharField(max_length=255)),
                ('pathPDF', models.CharField(max_length=255)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
