# Generated by Django 5.0 on 2024-01-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticsearchApp', '0002_article_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='auteurs',
        ),
        migrations.RemoveField(
            model_name='article',
            name='contenu',
        ),
        migrations.RemoveField(
            model_name='article',
            name='institutions',
        ),
        migrations.RemoveField(
            model_name='article',
            name='motsCles',
        ),
        migrations.RemoveField(
            model_name='article',
            name='pathPDF',
        ),
        migrations.RemoveField(
            model_name='article',
            name='references',
        ),
        migrations.RemoveField(
            model_name='article',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='article',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='article',
            name='urlPDF',
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
