# Generated by Django 5.0 on 2024-01-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticsearchApp', '0005_alter_article_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
