# Generated by Django 5.0 on 2024-01-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticsearchApp', '0003_remove_article_auteurs_remove_article_contenu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
