# Generated by Django 5.0 on 2024-01-31 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elasticsearchApp', '0006_article_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='new',
            new_name='approved',
        ),
    ]
